[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "raulsecante1", email = "raulsecante1@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=3.4.7",
]

[project.scripts]
mcp-server = "mcp_server.main:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
