import pydantic

class KnowledgeChunk (pydantic.BaseModel):
    '''
    knowledge fragments retrived from the document
    '''

    title: str
    key_term: str
    summary: str = pydantic.Field(min_length=1, max_length=500)

class Chapter (pydantic.BaseModel):
    '''
    chapter blueprints served for article outline
    '''

    title: str
    key_points: list[str]

class ArticleOutline (pydantic.BaseModel):
    '''
    skeleton of the article
    '''

    title: str
    chapters: list[Chapter]
    summary: list[str]

class FinalDraft (pydantic.BaseModel):
    '''
    the final output
    '''

    content: str
    outline: ArticleOutline

class QualityRubric (pydantic.BaseModel):
    '''
    evaluation result generated by the AI reviewer.
    '''

    clarity_score: float = pydantic.Field(ge=0, le=10)

    coverage_score: float = pydantic.Field(ge=0, le=10)

    actionable_feedback: list[str]

    overall_score: float = pydantic.Field(ge=0, le=10)

